language: php

php:
    - 7.0
    - 7.1
    - 7.2
    - 7.3
    - 7.4

dist: trusty
sudo: true


install: travis_retry composer install --no-interaction --prefer-source

#script: vendor/bin/phpunit --verbose